logging:
  level:
    com.example.inmemorycache: debug
    
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
